name: "Run notebooks"
inputs:
  python-version:
    required: true
  nox-session:
    required: true
  upload-name:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/run-tests/
      with:
        nox-session: ${{ inputs.nox-session }}
        python-version: ${{ inputs.python-version }}

    - name: Find executed notebooks
      shell: bash -l {0}
      run: |
        for f in $(git diff --name-only); do
          mkdir -p executed/$(dirname $f);
          cp $f executed/$(dirname $f);
        done
        ls -R executed/

    - name: Upload executed notebooks
      if: ${{ inputs.upload-name != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.upload-name }}
        path: executed/
        overwrite: true
